version: "3.8"
services:
  foxy_v3:
    image: benson/foxy:1.0
    container_name: foxy_v3
    command: /bin/bash -c "cd FOXY && streamlit run main.py & cd FOXY/GLIP && python main.py"
    volumes:
      - /home/mefae1:/workspace
      - /mnt:/mnt/share
    ports:
      - 3001:3001
      - 8501:8501
      - 8888:8888
      - 5000:5000
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
