credentials:
  usernames:
    mefae1:
      email: 
      name: mefae1
      password: '$2b$12$NngCSXRe5F9rxf2SkirEw.6xRr6Pt/iHhDvznIJ0cJCp1JsMVffIC' # To be replaced with hashed password
    mefad1:
      email: 
      name: mefad1
      password: '$2b$12$NngCSXRe5F9rxf2SkirEw.6xRr6Pt/iHhDvznIJ0cJCp1JsMVffIC' # To be replaced with hashed password
    mefad3:
      email: 
      name: mefad3
      password: '$2b$12$NngCSXRe5F9rxf2SkirEw.6xRr6Pt/iHhDvznIJ0cJCp1JsMVffIC' # To be replaced with hashed password
    mefad5:
      email: 
      name: mefad5
      password: '$2b$12$NngCSXRe5F9rxf2SkirEw.6xRr6Pt/iHhDvznIJ0cJCp1JsMVffIC' # To be replaced with hashed password
    admin:
      email: 
      name: admin
      password: '$2b$12$NngCSXRe5F9rxf2SkirEw.6xRr6Pt/iHhDvznIJ0cJCp1JsMVffIC' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com